development:
  protocol: 'http'
  host: '192.168.0.171'
  port: 8529
  password: 'root'
  username: 'root'
  database: 'sus_manager_development'

test:
  protocol: 'http'
  host: 'localhost'
  port: 8529
  password: ''
  username: 'root'
  database: 'sus_manager_test'
