development:
  protocol: 'http'
  host: 'localhost'
  port: 8529
  password: ''
  username: 'root'
  database: 'sus_manager_development'

test:
  protocol: 'http'
  host: 'localhost'
  port: 8529
  password: ''
  username: 'root'
  database: 'sus_manager_test'
